apiVersion: v1
kind: Secret
metadata:
  name: globalmedx-secrets
  namespace: globalmedx
type: Opaque
data:
  # Base64 encoded: mongodb://mongodb-service:27017/globalmedx
  MONGODB_URI: bW9uZ29kYjovL21vbmdvZGItc2VydmljZToyNzAxNy9nbG9iYWxtZWR4
  # Base64 encoded: globalmedx_super_secret_jwt_key_2026
  JWT_SECRET: Z2xvYmFsbWVkeF9zdXBlcl9zZWNyZXRfand0X2tleV8yMDI2
  # Base64 encoded: globalmedx-dev-token
  VAULT_TOKEN: Z2xvYmFsbWVkeC1kZXYtdG9rZW4=
