input {
  tcp {
    port => 5044
    codec => json
  }
}

filter {
  # Add filters to parse custom log headers if necessary
  if [service] == "globalmedx-backend" {
    mutate {
      add_tag => [ "backend" ]
    }
  }
}

output {
  elasticsearch {
    hosts => ["elasticsearch:9200"]
    index => "globalmedx-logs-%{+YYYY.MM.dd}"
  }
  stdout {
    codec => rubydebug
  }
}
